### ISSUE TITLE
hi, if possible to run armhf docker or chroot on Cavium ThunderX?

### ISSUE THREAD

**Issue by yangxuan8282** [caviumnetworks/thunderx-linux#1]
I want to compile some armhf package on Cavium ThunderX, and have tried some different OS (ubuntu, centos, debian 9, opensuse 42.3) on packet.net , but seems it can't run armhf container.

**Comment by semihalf-biernacki-radoslaw** [comment]
If your docker image refers to armhf, it probably means that it uses a ARMv6 or ARMv7 32bit instruction set with hardware floating point. ThunderX is ARMv8 machine working in 64bit.
You simply cannot run (docker) container with different instruction set than host machine.
You either need to use emulation like Qemu with softmmu arch or you need a ARMv7 host machine.
